### ISSUE TITLE
Erro ao Gerar Código do Boleto. 

### ISSUE THREAD

**Issue by rodrigobg** [AndyTargino/MercadoPago-API#2]
Olá obrigado por disponibilizar este script de checkout do MP, seu trabalho ficou excelente. Eu estou fazendo alguns testes em SandBox e está dando erro na geração do boleto. Será que preciso preencher mais alguma coisa no index.php pra funcionar perfeito, a a minha chave publica no caso? Agradeço muito se puder me dar um help. E gostaria de sugerir o retorno automático do PIX, tipo quando a pessoa pagar o pix, ele automaticamente mudar o status na tela como "pago". 

Sucesso!!!

**Comment by AndyTargino** [comment]
Olá! Sugeriria que você identificasse claramente o problema e procurasse corrigi-lo. Caso seja possível, sua contribuição para a biblioteca seria muito apreciada. Agradeço antecipadamente!
